app = "ultraviolet-app-rryx5a"  # Your Fly.io app name

primary_region = "dfw"  # Choose a region close to you (e.g., iad, dfw, sjc)

[build]
  image = "ultraviolet-app-rryx5a"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
